"""曲线简称常量定义。"""

_VP_MNEMONICS = ("DT", "AC", "DTC", "DTCO", "DTC1")
_VS_MNEMONICS = ("DTS", "DTSM", "DTS1")
_RHO_MNEMONICS = ("DEN", "RHOB", "RHOZ")
_GR_MNEMONICS = ("GR", "GR_CAL")
_POR_MNEMONICS = ("POR", "PHIT", "PHIE")
_PERM_MNEMONICS = ("PERM", "PERM_COATES_FFI")
_SW_MNEMONICS = ("SW", "SWE", "SWT")
