"""曲线简称常量定义。"""

_CALI_MNEMONICS = ("BS", "CALI", "HDAR", "HCAL")
_VP_MNEMONICS = ("DT", "AC", "DTC", "DTCO")
_VS_MNEMONICS = ("DTS", "DTSM", "DTSH")
_RHO_MNEMONICS = ("DEN", "RHOB", "RHOZ", "HDRA")
_GR_MNEMONICS = ("GR", "GR_CAL")
_POR_MNEMONICS = ("POR", "PHIE", "PHIT", "PHIE_HILT")
_PERM_MNEMONICS = ("PERM", "PERM_COATES_FFI")
_SW_MNEMONICS = ("SW", "SWE", "SWT", "SW_HILT")
